version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'meteor_app'
    container_name: 'meteor_app'
    stdin_open: true
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://ferretdb:27017/meteor
      PORT: 3000
  nginx:
    image: nginx
    hostname: 'nginx'
    container_name: 'nginx'
    ports:
      - 8888:8888
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres:14.0
    hostname: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=meteor
  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:latest
    hostname: 'ferretdb'
    container_name: 'ferretdb'
    restart: 'on-failure'
    command:
      [
        '-listen-addr=:27017',
        '-postgresql-url=postgres://postgres@postgres:5432/meteor',
      ]
    ports:
      - 27017:27017
  setup:
    image: postgres:14.0
    hostname: 'setup'
    container_name: 'setup'
    restart: 'on-failure'
    depends_on:
      - 'postgres'
    entrypoint: ["sh", "-c", "psql -h postgres -U postgres -d meteor -c 'CREATE SCHEMA IF NOT EXISTS tasks'"]
